// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkn5KdqdaW6SfIP0bnakxFTGrDGDx7sk0',
    appId: '1:332958643290:web:d43fe42fa2b42b17f01463',
    messagingSenderId: '332958643290',
    projectId: 'mojtama-3e50c',
    authDomain: 'mojtama-3e50c.firebaseapp.com',
    storageBucket: 'mojtama-3e50c.appspot.com',
    measurementId: 'G-E0KY1BG9Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmLvifiaoS2yR206wGclRhVwKXd37L0Mg',
    appId: '1:332958643290:android:227e1b36255d5dc0f01463',
    messagingSenderId: '332958643290',
    projectId: 'mojtama-3e50c',
    storageBucket: 'mojtama-3e50c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUx1xkML15ADK4lrPJBZkkJLYtCLSqw6A',
    appId: '1:332958643290:ios:b3f54afd8506d73df01463',
    messagingSenderId: '332958643290',
    projectId: 'mojtama-3e50c',
    storageBucket: 'mojtama-3e50c.appspot.com',
    iosClientId: '332958643290-9kk34brid23fnl5chnruug38t9blkrcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mojtama',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUx1xkML15ADK4lrPJBZkkJLYtCLSqw6A',
    appId: '1:332958643290:ios:b3f54afd8506d73df01463',
    messagingSenderId: '332958643290',
    projectId: 'mojtama-3e50c',
    storageBucket: 'mojtama-3e50c.appspot.com',
    iosClientId: '332958643290-9kk34brid23fnl5chnruug38t9blkrcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.mojtama',
  );
}
